### ISSUE TITLE
User Sign-in/Register

### ISSUE THREAD

**Issue by mosihere** [mosihere/movie-raters#1]
RESTful User Register/Sign-in
probably using token-based auth

**Comment by franciszek-szeptycki** [comment]
Hey, could you assign me to this issue?

**Comment by mosihere** [comment]
Done #2

**Comment by mosihere** [comment]
> Hey, could you assign me to this issue?

Uh sorry! Already done dude.
You know front-end ?
I think vue would be nice for front-end.
by the way, feel free to open issues.
we could work together if u want :)

**Comment by franciszek-szeptycki** [comment]
> > Hey, could you assign me to this issue?
> 
> Uh sorry! Already done dude. You know front-end ? I think vue would be nice for front-end. by the way, feel free to open issues. we could work together if u want :)

Hey, I am not really into frontend

**Comment by mosihere** [comment]
> > > Hey, could you assign me to this issue?
> 
> > 
> 
> > Uh sorry! Already done dude. You know front-end ? I think vue would be nice for front-end. by the way, feel free to open issues. we could work together if u want :)
> 
> 
> 
> Hey, I am not really into frontend


Ok then, If you have any idea for back, open issue and work on it if you into it :)
